FROM python:3.6-slim

MAINTAINER shuchi.ajay@gmail.com

COPY . /docker_pytest_demo

WORKDIR /docker_pytest_demo

RUN pip install --no-cache-dir -r requirements.txt

RUN ["pytest", "-v", "--junitxml=reports/result.xml"]

CMD tail -f /dev/null